let defaultType = {
    fillStyle: "rgb(255, 255, 255)",
    strokeStyle: "rgb(255, 255, 255)",
    size: 5,
    speed: 5,
    visualRange: 75,
    separationRadius: 20,
    separationWeight: 0.05,
    alignmentWeight: 0.05,
    cohesionWeight: 0.005,
    escapeWeight: 0.05,
    aggressionWeight: 0.005,
    aggrsesionCap: 0.5,
    aggression: 0,
    friendly: false,
    attack: false,
}

let types = [
    {
        fillStyle: "rgb(160, 140, 60)",
        strokeStyle: "rgb(160, 140, 60)",
        size: 5,
        speed: 18,
        visualRange: 75,
        separationRadius: 20,
        separationWeight: 0.5,
        alignmentWeight: 0.025,
        cohesionWeight: 0.05,
        escapeWeight: 0.05,
        aggressionWeight: 0.005,
        aggressionCap: 0.5,
        aggression: -0.5,
        friendly: false,
        attack: false,
    },
    {
        fillStyle: "rgb(150, 150, 150)",
        strokeStyle: "rgb(150, 150, 150)",
        size: 5,
        speed: 5,
        visualRange: 150,
        separationRadius: 20,
        separationWeight: 0.5,
        alignmentWeight: 0.01,
        cohesionWeight: 0.01,
        escapeWeight: 0.005,
        aggressionWeight: 0.005,
        aggressionCap: 0.5,
        aggression: 0,
        friendly: false,
        attack: false,
    },
    {
        fillStyle: "rgb(255, 0, 255)",
        strokeStyle: "rgb(255, 0, 255)",
        size: 10,
        speed: 2,
        visualRange: 150,
        separationRadius: 20,
        separationWeight: 0.01,
        alignmentWeight: -0.01,
        cohesionWeight: -0.01,
        escapeWeight: 0.005,
        aggressionWeight: 0.005,
        aggressionCap: 0.5,
        aggression: -5,
        friendly: false,
        attack: true,
    },
    {
        fillStyle: "rgb(255, 0, 50)",
        strokeStyle: "rgb(255, 0, 50)",
        size: 2,
        speed: 6,
        visualRange: 75,
        separationRadius: 20,
        separationWeight: 0.05,
        alignmentWeight: 0.05,
        cohesionWeight: 0.005,
        escapeWeight: 0.05,
        aggressionWeight: 0.05,
        aggressionCap: 5,
        aggression: -0.01,
        friendly: false,
        attack: false,
    },
    {
        fillStyle: "rgb(0, 75, 50)",
        strokeStyle: "rgb(0, 75, 50)",
        size: 25,
        speed: 2,
        visualRange: 150,
        separationRadius: 20,
        separationWeight: 0,
        alignmentWeight: 0,
        cohesionWeight: 0,
        escapeWeight: 0,
        aggressionWeight: 1,
        aggressionCap: 0.01,
        aggression: -50,
        friendly: false,
        attack: false,
    },
    {
        fillStyle: "rgb(45, 135, 90)",
        strokeStyle: "rgb(45, 135, 90)",
        size: 3,
        speed: 4,
        visualRange: 150,
        separationRadius: 20,
        separationWeight: 0.05,
        alignmentWeight: 0.05,
        cohesionWeight: 0.005,
        escapeWeight: 0.05,
        aggressionWeight: 0.05,
        aggressionCap: 0.01,
        aggression: -0.01,
        friendly: false,
        attack: false,
    },
    {
        fillStyle: "rgb(200, 0, 120)",
        strokeStyle: "rgb(200, 0, 120)",
        size: 5,
        speed: 5,
        visualRange: 150,
        separationRadius: 20,
        separationWeight: 0.5,
        alignmentWeight: 0.01,
        cohesionWeight: 0.01,
        escapeWeight: 0.005,
        aggressionWeight: 0.005,
        aggressionCap: 0.5,
        aggression: 0,
        friendly: false,
        attack: false,
    },
    {
        fillStyle: "rgb(80, 120, 200)",
        strokeStyle: "rgb(80, 120, 200)",
        size: 3,
        speed: 6,
        visualRange: 150,
        separationRadius: 20,
        separationWeight: 0.5,
        alignmentWeight: 0.05,
        cohesionWeight: 0.01,
        escapeWeight: 0.005,
        aggressionWeight: 0.005,
        aggressionCap: 0.5,
        aggression: 0,
        friendly: false,
        attack: false,
    },
    {
        fillStyle: "rgb(244, 255, 142)",
        strokeStyle: "rgb(244, 255, 142)",
        size: 50,
        speed: 25,
        visualRange: 150,
        separationRadius: 20,
        separationWeight: 0.5,
        alignmentWeight: 0.05,
        cohesionWeight: 0.01,
        escapeWeight: 0.005,
        aggressionWeight: 0.005,
        aggressionCap: 0.5,
        aggression: -500,
        friendly: false,
        attack: true,
    },
]